# Generated by Django 2.2.4 on 2019-09-05 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
